version: 2
workflows:
  version: 2
  test:
    jobs:
      #- test-3.7
      #- test-3.6
      #- test-3.5
      #- test-2.7
      - melodic:
          #requires:
          #  - test-2.7
jobs:
  test-3.6: &test-template
    environment:
      COLUMNS: 160
      # default is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: |
            git clone --recursive https://github.com/duckietown/duckietown-world.git
            cd duckietown-world
            pip install -r requirements.txt
            python setup.py develop --no-deps
  melodic:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build duckietown-fplan
          command: |
            cd ..
            catkin build
      - test-results-store:
          path: out-comptests/junit

      - store_artifacts:
          path: out-comptests/duckietown_world_tests
          destination: duckietown_world_tests
          
      - store_artifacts:
          path: artifacts
          destination: artifacts

      - store_artifacts:
          path: out_coverage
          destination: coverage

      - store_artifacts:
          path: notebooks
          destination: notebooks
    working_directory: ~/src
  test-3.5:
    <<: *test-template
    docker:
      - image: python:3.5
  test-2.7:
    <<: *test-template
    docker:
    - image: python:2.7
  test-3.7:
    <<: *test-template
    docker:
    - image: python:3.7
  test-circle-2.7:
    <<: *test-template
    docker:
    - image: circle/python
