version: 2
workflows:
  version: 2
  test:
    jobs:
      - melodic
      #- test-3.7
      #- test-3.6
      #- test-3.5
      - test-2.7:
          requires:
            - melodic
jobs:
  test-3.6: &test-template
    environment:
      COLUMNS: 160
      # default is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: |
            git clone --recursive https://github.com/duckietown/duckietown-world.git
            cd duckietown-world
            pip install -r requirements.txt
            python setup.py develop --no-deps
      - run:
          name: Build duckietown-fplan
          command: |
            cd src
            pwd
            ls
  melodic:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
  test-3.5:
    <<: *test-template
    docker:
      - image: python:3.5
  test-2.7:
    <<: *test-template
    docker:
    - image: python:2.7
  test-3.7:
    <<: *test-template
    docker:
    - image: python:3.7
  test-circle-2.7:
    <<: *test-template
    docker:
    - image: circle/python
